import CommonLayout from '@/layouts/common'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <CommonLayout>
      {children}
    </CommonLayout>
  )
}
